---
# Install and upgrade to latest kernel
- name: Install ELREPO key for CentOS
  rpm_key:
    key: "https://www.elrepo.org/RPM-GPG-KEY-elrepo.org"
    state: present
  when: ansible_distribution == "CentOS"
  tags:
    - packages
    - kernel
    - bootstrap

- name: Install ELREPO repository for CentOS
  yum:
    name: "{{ item }}"
    state: present
  when: ansible_distribution == "CentOS"
  with_items:
    - 'http://www.elrepo.org/elrepo-release-7.0-2.el7.elrepo.noarch.rpm'
    - 'yum-plugin-fastestmirror'
  tags:
    - packages
    - kernel
    - bootstrap

- name: Install latest kernel from ELREPO repo for CentOS
  yum:
    name: "kernel-ml"
    state: latest
    update_cache: yes
    enablerepo: elrepo-kernel
  when: ansible_distribution == "CentOS"
  register: kernel_ml_update
  tags:
    - packages
    - kernel
    - bootstrap

- name: Update grub bootloader with latest kernel for CentOS
  command: "grub2-set-default 0"
  when: ansible_distribution == "CentOS" and (kernel_ml_update|succeeded)
  register: grub_update
  tags:
    - packages
    - kernel
    - bootstrap

- name: Remove old kernels for CentOS
  command: "package-cleanup -y --oldkernels --count=1"
  when: ansible_distribution == "CentOS" and (kernel_ml_update|succeeded) and grub_update|succeeded
  tags:
    - packages
    - kernel
    - bootstrap
    - cleanup
