---
- include: metadata.yml
  tags:
    - bootstrap

- include: sudo.yml
  tags:
    - sudo
    - bootstrap

- include: sshd.yml
  tags:
    - ssh
    - bootstrap

# Install OS packages
- include: "{{ ansible_distribution }}-packages.yml"
  tags:
    - always
    - packages
    - bootstrap

# Install updates
- include: "{{ansible_distribution}}-updates.yml"
  tags:
    - packages
    - bootstrap

- include: network.yml
  tags:
    - packages
    - network
    - bootstrap

- include: "{{ ansible_distribution }}-kernel.yml"
  tags:
    - packages
    - kernel
    - bootstrap

# Install motd
- include: "{{ ansible_distribution }}-motd.yml"
  tags:
    - bootstrap

- include: cleanup.yml
  tags:
    - packages
    - kernel
    - bootstrap
    - cleanup
