---
# Install and configure ZooKeeper
- name: Install ZooKeeper on host
  hosts:  all
  gather_facts: yes
  serial: "{{ serial | default(1) }}"

##  vars_files:
##    - "group_vars/zookeeper.yml"

  roles:
    - common
    - zookeeper
